// LGraphEventMode — matches ComfyUI_frontend/src/lib/litegraph/src/types/globalEnums.ts
export type NodeMode = 0 | 1 | 2 | 3 | 4 // ALWAYS | ON_EVENT | NEVER | ON_TRIGGER | BYPASS

// ISlotType — matches ComfyUI_frontend/src/lib/litegraph/src/interfaces.ts
// String for named types ("IMAGE", "LATENT", …); number for legacy primitive types
export type SlotType = string | number

export interface WorkflowLink {
  id: number
  fromNodeId: number
  fromSlot: number
  toNodeId: number
  toSlot: number
  type: SlotType
}

export interface NodeInputSlot {
  name: string
  type: SlotType
  link: number | null
  slot_index?: number
  widget?: { name: string }
  // RenderShape.HollowCircle (7) marks an optional connection input.
  // Set by ComfyUI_frontend/src/services/litegraphService.ts when the input
  // comes from INPUT_TYPES()['optional'] (ComfyUI/nodes.py).
  // Source enum: ComfyUI_frontend/src/lib/litegraph/src/types/globalEnums.ts
  shape?: number
}

export interface NodeOutputSlot {
  name: string
  type: SlotType
  links: number[] | null // null when no connections, per LiteGraph serialization
  slot_index?: number
  widget?: { name: string }
}

export interface WorkflowNode {
  id: number
  type: string
  pos?: [number, number]      // optional only because broken workflows may omit it
  size?: [number, number]     // same — always a tuple when present
  mode?: NodeMode
  inputs?: NodeInputSlot[]
  outputs?: NodeOutputSlot[]
  widgets_values?: unknown[]
  flags?: Record<string, unknown>
  properties?: Record<string, unknown>
  title?: string
  order?: number
}

export interface GraphWorkflow {
  nodes: WorkflowNode[]
  // Link tuple: [id, fromNodeId, fromSlot, toNodeId, toSlot, type]
  links: [number, number, number, number, number, SlotType][]
  version?: number
  last_node_id?: number
  last_link_id?: number
}

export type Severity = 'error' | 'warning' | 'info'

export type FixType =
  | 'null-widget-value'
  | 'widget-value-out-of-range'
  | 'ghost-link'
  | 'link-type-metadata'
  | 'stale-media-ref'
  | 'bypassed-node'
  | 'type-mismatch'
  | 'disconnected-input'

export interface Issue {
  severity: Severity
  nodeId?: number
  nodeType?: string
  message: string
  detail?: string
  suggestion?: string
  fixable?: boolean
  fixType?: FixType
}

export interface AnalysisResult {
  format: 'graph' | 'api' | 'unknown'
  nodeCount: number
  linkCount: number
  issues: Issue[]
  canRun: boolean
}

// ---------------------------------------------------------------------------
// /object_info schema types
// ---------------------------------------------------------------------------

export interface NodeInputConfig {
  default?: unknown
  min?: number
  max?: number
  step?: number
  multiline?: boolean
  [key: string]: unknown
}

export interface NodeSchemaDef {
  input: {
    required?: Record<string, [string | string[], NodeInputConfig?]>
    optional?: Record<string, [string | string[], NodeInputConfig?]>
  }
  output: string[]
  output_name?: string[]
  category: string
  output_node?: boolean
}

export type ObjectInfo = Record<string, NodeSchemaDef>

// ---------------------------------------------------------------------------
// Static offline schema types (src/lib/nodes_schema.json)
// Generated by scripts/build_schema.py from nodes_lib/ Python sources.
// ---------------------------------------------------------------------------

export interface StaticNodeSchema {
  category: string
  inputs: {
    required: Record<string, string>
    optional: Record<string, string>
  }
  outputs: string[]
  /** INT input names that cause the frontend to inject an extra COMBO slot after
   *  them in widgets_values (control_after_generate widget — frontend-only). */
  control_after_generate?: string[]
}

export type StaticSchema = Record<string, StaticNodeSchema>
