#!/usr/bin/env python3
"""
extract-node-type-map.py — derive fix-engine routing tables from nodes_schema.json.

Reads:  src/lib/nodes_schema.json  (generated by build_schema.py)
Writes: src/lib/shared/node-type-map.json

No runtime dependencies. No ComfyUI installation required.
Run after build_schema.py (or let update_schema.sh call both in sequence).

Output tables:

  sourceMap[outType] = list of nodes that produce outType, sorted simplest-first.
    Each entry: { class, outputSlot, widgetDefaults, requiredInputs }
    requiredInputs: connection-only inputs the engine must recursively satisfy.

  conversionMap[srcType][dstType] = list of nodes that accept srcType and produce dstType.
    Each entry: { class, inputSlot, inputSlotIndex, outputSlot, extraInputs }
    inputSlotIndex: connection-slot index of the primary input (= its position in
                    the workflow JSON node.inputs[] array).
    extraInputs:    other required connection inputs, same slotIndex convention.

slotIndex convention: position among connection-type inputs only.
INT/FLOAT/STRING/BOOLEAN/COMBO are widget inputs and are NOT counted.
This matches the workflow JSON node.inputs[] array index.
"""

import json
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
INPUT  = REPO_ROOT / 'src' / 'lib' / 'nodes_schema.json'
OUTPUT = REPO_ROOT / 'src' / 'lib' / 'shared' / 'node-type-map.json'

WIDGET_TYPES = {'INT', 'FLOAT', 'STRING', 'BOOLEAN', 'COMBO'}

# Output types that are too generic or internal for the fix engine to route.
SKIP_OUTPUT_TYPES = {'*', 'COMBO', 'STRING', 'INT', 'FLOAT', 'BOOLEAN', 'HIDDEN'}

# Conversion nodes with more extra required connection inputs than this are
# too complex to auto-insert reliably — skip them in conversionMap.
MAX_EXTRA_CONN_INPUTS = 2

schema: dict = json.loads(INPUT.read_text(encoding='utf-8'))

source_map: dict[str, list]                       = defaultdict(list)
conversion_map: dict[str, dict[str, list]]        = defaultdict(lambda: defaultdict(list))

for node_type, node_def in schema.items():
    outputs: list[str] = node_def.get('outputs', [])
    if not outputs:
        continue

    required: dict[str, str] = node_def['inputs'].get('required', {})

    # Classify required inputs.
    # Connection-slot index = position among non-widget inputs only.
    conn_inputs: list[tuple[str, str]] = []   # [(name, type)]
    widget_defaults: dict[str, None]   = {}

    for name, type_str in required.items():
        if type_str in WIDGET_TYPES:
            widget_defaults[name] = None
        else:
            conn_inputs.append((name, type_str))

    # ── sourceMap ────────────────────────────────────────────────────────────
    required_inputs_entry = [
        {'name': n, 'type': t, 'slotIndex': i}
        for i, (n, t) in enumerate(conn_inputs)
    ]
    for out_idx, out_type in enumerate(outputs):
        if out_type in SKIP_OUTPUT_TYPES:
            continue
        source_map[out_type].append({
            'class':          node_type,
            'outputSlot':     out_idx,
            'widgetDefaults': widget_defaults,
            'requiredInputs': required_inputs_entry,
        })

    # ── conversionMap ─────────────────────────────────────────────────────────
    if not conn_inputs:
        continue

    for conn_idx, (src_name, src_type) in enumerate(conn_inputs):
        extras = [
            {'name': n, 'type': t, 'slotIndex': i}
            for i, (n, t) in enumerate(conn_inputs)
            if n != src_name
        ]
        if len(extras) > MAX_EXTRA_CONN_INPUTS:
            continue
        for out_idx, out_type in enumerate(outputs):
            if out_type in SKIP_OUTPUT_TYPES or out_type == src_type:
                continue
            conversion_map[src_type][out_type].append({
                'class':          node_type,
                'inputSlot':      src_name,
                'inputSlotIndex': conn_idx,
                'outputSlot':     out_idx,
                'extraInputs':    extras,
            })

# Sort sourceMap entries by complexity so the fix engine's sources[0] is simplest.
for entries in source_map.values():
    entries.sort(key=lambda e: len(e['requiredInputs']))

result = {
    'conversionMap': {
        src: dict(sorted(targets.items()))
        for src, targets in sorted(conversion_map.items())
    },
    'sourceMap': dict(sorted(source_map.items())),
}

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(json.dumps(result, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')

src_count  = sum(len(v) for v in result['sourceMap'].values())
conv_count = sum(
    sum(len(v) for v in targets.values())
    for targets in result['conversionMap'].values()
)
print(f'OK: {OUTPUT.relative_to(REPO_ROOT)}')
print(f'  sourceMap:     {len(result["sourceMap"])} output types, {src_count} entries')
print(f'  conversionMap: {len(result["conversionMap"])} source types, {conv_count} entries')
